export type Product = {
  name: string;
  category: string;
}

export const PRODUCTS_BY_NAME = {
  Banan: { name: "Banan", category: "Fruits" },
  Jabłko: { name: "Jabłko", category: "Fruits" },
  Kiwi: { name: "Kiwi", category: "Fruits" },
  Pomarańcza: { name: "Pomarańcza", category: "Fruits" },
  Brzoskwinia: { name: "Brzoskwinia", category: "Fruits" },
  Imbir: { name: "Imbir", category: "Fruits" },
  Gruszka: { name: "Gruszka", category: "Fruits" },
  Borówki: { name: "Borówki", category: "Fruits" },
  Cytryna: { name: "Cytryna", category: "Fruits" },
  Kalarepa: { name: "Kalarepa", category: "Vegetables" },
  Pietruszka: { name: "Pietruszka", category: "Vegetables" },
  Szczypiorek: { name: "Szczypiorek", category: "Vegetables" },
  Koperek: { name: "Koperek", category: "Vegetables" },
  Pomidory_koktailowe: { name: "Pomidory koktailowe", category: "Vegetables" },
  Pomidor: { name: "Pomidor", category: "Vegetables" },
  Dynia: { name: "Dynia", category: "Vegetables" },
  Cukinia: { name: "Cukinia", category: "Vegetables" },
  Ogórek: { name: "Ogórek", category: "Vegetables" },
  Cebula: { name: "Cebula", category: "Vegetables" },
  Szalotka: { name: "Szalotka", category: "Vegetables" },
  Czosnek: { name: "Czosnek", category: "Vegetables" },
  Papryka: { name: "Papryka", category: "Vegetables" },
  Marchewka: { name: "Marchewka", category: "Vegetables" },
  Seler_naciowy: { name: "Seler naciowy", category: "Vegetables" },
  Rzodkiewka: { name: "Rzodkiewka", category: "Vegetables" },
  Roszponka: { name: "Roszponka", category: "Vegetables" },
  Rukola: { name: "Rukola", category: "Vegetables" },
  Szpinak: { name: "Szpinak", category: "Vegetables" },
  Szparagi: { name: "Szparagi", category: "Vegetables" },
  Bazylia: { name: "Bazylia", category: "Vegetables" },
  Papryczki: { name: "Papryczki", category: "Vegetables" },
  Jarmuz: { name: "Jarmuz", category: "Vegetables" },
  Oliwki: { name: "Oliwki", category: "Vegetables" },
  Bataty: { name: "Bataty", category: "Vegetables" },
  Pieczarki: { name: "Pieczarki", category: "Vegetables" },
  Fasolka_czerwona: { name: "Fasolka czerwona", category: "Vegetables" },
  Kukurydza: { name: "Kukurydza", category: "Vegetables" },
  Kolendra: { name: "Kolendra", category: "Vegetables" },
  Ziemniaki: { name: "Ziemniaki", category: "Vegetables" },
  Kalafior: { name: "Kalafior", category: "Vegetables" },
  Pietruszka_korzeń: { name: "Pietruszka korzeń", category: "Vegetables" },
  Bób: { name: "Bób", category: "Vegetables" },
  Truskawki_mrozone: { name: "Truskawki mrozone", category: "Frost" },
  Owoce_mrozone: { name: "Owoce mrozone", category: "Frost" },
  Warzywa_mrozone: { name: "Warzywa mrozone", category: "Frost" },
  Krewetki: { name: "Krewetki", category: "Frost" },
  Pierogi_z_truskawkami: { name: "Pierogi z truskawkami", category: "Frost" },
  Pierogi_ruskie: { name: "Pierogi ruskie", category: "Frost" },
  Groszek_mrozony: { name: "Groszek mrozony", category: "Frost" },
  Pomidory_suszone: { name: "Pomidory suszone", category: "Konserwy" },
  Oliwa: { name: "Oliwa", category: "Konserwy" },
  Ciecierzyca: { name: "Ciecierzyca", category: "Konserwy" },
  Pomidory_w_puszce: { name: "Pomidory w puszce", category: "Konserwy" },
  Kapary: { name: "Kapary", category: "Konserwy" },
  Przecier_pomidorowy: { name: "Przecier pomidorowy", category: "Konserwy" },
  Szproty: { name: "Szproty", category: "Konserwy" },
  Pesto: { name: "Pesto", category: "Konserwy" },
  Mleko_sojowe: { name: "Mleko sojowe", category: "Dairy" },
  Mleko: { name: "Mleko", category: "Dairy" },
  Mleko_migdałowe: { name: "Mleko_migdałowe", category: "Dairy" },
  Jajka: { name: "Jajka", category: "Dairy" },
  Skyr: { name: "Skyr", category: "Dairy" },
  Twaróg: { name: "Twaróg", category: "Dairy" },
  Jogurt_naturalny: { name: "Jogurt naturalny", category: "Dairy" },
  Jogurt_grecki: { name: "Jogurt grecki", category: "Dairy" },
  Masło: { name: "Masło", category: "Dairy" },
  Serek_wiejski: { name: "Serek wiejski", category: "Dairy" },
  Mozzarella: { name: "Mozzarella", category: "Dairy" },
  Ser_zółty: { name: "Ser żółty", category: "Dairy" },
  Ser_kozi: { name: "Ser kozi", category: "Dairy" },
  Ser_feta: { name: "Ser feta", category: "Dairy" },
  Ser_twarożkowy: { name: "Ser twarożkowy", category: "Dairy" },
  Mascarpone: { name: "Mascarpone", category: "Dairy" },
  Śmietana36: { name: "Śmietana 36", category: "Dairy" },
  Śmietana18: { name: "Śmietana 18", category: "Dairy" },
  Kefir: { name: "Kefir", category: "Dairy" },
  Grana_Padano: { name: "Grana Padano", category: "Dairy" },
  Mozzarella_tarta: { name: "Mozzarella tarta", category: "Dairy" },
  Drozdze: { name: "Drozdze", category: "Dairy" },
  Skyr_owocowy: { name: "Skyr owocowy", category: "Dairy" },
  Makadamia: { name: "Makadamia", category: "Bakalie" },
  Orzechy_laskowe: { name: "Orzechy laskowe", category: "Bakalie" },
  Orzechy_włoskie: { name: "Orzechy włoskie", category: "Bakalie" },
  Orzechy_nerkowca: { name: "Orzechy nerkowca", category: "Bakalie" },
  Orzechy_ziemne: { name: "Orzechy ziemne", category: "Bakalie" },
  Migdały: { name: "Migdały", category: "Bakalie" },
  Orzechy_arachidowe: { name: "Orzechy arachidowe", category: "Bakalie" },
  Orzechy_brazylijskie: { name: "Orzechy brazylijskie", category: "Bakalie" },
  Pistacje: { name: "Pistacje", category: "Bakalie" },
  Makaron_włoski: { name: "Makaron włoski", category: "Zboza" },
  Makaron_razowy: { name: "Makaron razowy", category: "Zboza" },
  Ryż: { name: "Ryż", category: "Zboza" },
  Kasza_gryczana: { name: "Kasza gryczana", category: "Zboza" },
  Kasza_jaglana: { name: "Kasza jaglana", category: "Zboza" },
  Kasza_manna: { name: "Kasza manna", category: "Zboza" },
  Kasza_jęczmienna: { name: "Kasza jęczmienna", category: "Zboza" },
  Kasza_owsiana: { name: "Kasza owsiana", category: "Zboza" },
  Kasza_perłowa: { name: "Kasza perłowa", category: "Zboza" },
  Ryz_basmati: { name: "Ryż basmati", category: "Zboza" },
  Ryz_parboiled: { name: "Ryż parboiled", category: "Zboza" },
  Ryz_brązowy: { name: "Ryż brązowy", category: "Zboza" },
  Ryz_arborio: { name: "Ryż arborio", category: "Zboza" },
  Tagliatelle: { name: "Tagliatelle", category: "Zboza" },
  Spaghetti: { name: "Spaghetti", category: "Zboza" },
  Penne: { name: "Penne", category: "Zboza" },
  Makaron_świderki: { name: "Makaron świderki", category: "Zboza" },
  Kurczak: { name: "Kurczak", category: "Meat" },
  Wołowina: { name: "Wołowina", category: "Meat" },
  Wieprzowina: { name: "Wieprzowina", category: "Meat" },
  Indyk: { name: "Indyk", category: "Meat" },
  Kaczka: { name: "Kaczka", category: "Meat" },
  Gęś: { name: "Gęś", category: "Meat" },
  Królik: { name: "Królik", category: "Meat" },
  Jagnięcina: { name: "Jagnięcina", category: "Meat" },
  Baranina: { name: "Baranina", category: "Meat" },
  Kiełbasa: { name: "Kiełbasa", category: "Meat" },
  Salami: { name: "Salami", category: "Meat" },
  Salami_picante: { name: "Salami picante", category: "Meat" },
  Szynka: { name: "Szynka", category: "Meat" },
  Boczek: { name: "Boczek", category: "Meat" },
  Łosoś: { name: "Łosoś", category: "Meat" },
  Makrela: { name: "Makrela", category: "Meat" },
  Tuńczyk: { name: "Tuńczyk", category: "Meat" },
  Sardynki: { name: "Sardynki", category: "Meat" },
  Tortille: { name: "Tortille", category: "Pieczywo" },
  Chleb: { name: "Chleb", category: "Pieczywo" },
  Bułki: { name: "Bułki", category: "Pieczywo" },
  Wafle_ryżowe: { name: "Wafle ryżowe", category: "Pieczywo" },
  Sos_sojowy: { name: "Sos sojowy", category: "Spices" },
  Oregano: { name: "Oregano", category: "Spices" },
  Kmin_rzymski: { name: "Kmin rzymski", category: "Spices" },
  Kolendra_mielona: { name: "Kolendra mielona", category: "Spices" },
  Cynamon: { name: "Cynamon", category: "Spices" },
  Kurkuma: { name: "Kurkuma", category: "Spices" },
  Chili: { name: "Chili", category: "Spices" },
  Kostka_rosołowa: { name: "Kostka rosołowa", category: "Spices" },
  Wino_białe: { name: "Wino białe", category: "Alco" },
  Wino_czerwone: { name: "Wino czerwone", category: "Alco" },
  Piwo: { name: "Piwo", category: "Alco" },
  Wódka: { name: "Wódka", category: "Alco" },
  Whiskey: { name: "Whiskey", category: "Alco" },
  Rum: { name: "Rum", category: "Alco" },
  Pasta_do_zebow: { name: "Pasta do zębów", category: "Chemia" },
  Mydlo: { name: "Mydło", category: "Chemia" },
};

export const PRODUCTS = Object.values(PRODUCTS_BY_NAME);
